#!/usr/bin/env bash
# Install objdiff-cli as a COPY, and record what was installed.
#
# The hazard this exists for, measured on one box on 2026-08-12:
#
#   ~/.local/bin/objdiff-cli -> <checkout>/target/release/objdiff-cli
#
# A symlink into a shared build tree means any `cargo build --release` in that
# checkout silently reprices every measurement anyone takes through PATH. It
# happened at 05:56:47 between two lane verifications; the two lanes were scored
# on different rulers and neither run could tell. The binary on PATH was also not
# a clean build of any commit -- its provenance was "whatever a peer last built".
#
# So: copy, never link, and write a manifest beside the copy saying which commit
# and which bytes. `objdiff-cli --version` prints the same identity, and every
# report generated by it carries it in `provenance`, so three independent places
# have to agree before a measurement is in doubt.
#
#   scripts/install-objdiff-cli.sh                       # build, then install to ~/.local/bin
#   scripts/install-objdiff-cli.sh --dest /usr/local/bin
#   scripts/install-objdiff-cli.sh --from path/to/objdiff-cli --no-build
#
# Refuses to replace a symlink unless --replace-symlink is given: someone chose
# that link, and silently converting it to a copy changes what every other
# process on the box measures with.
set -euo pipefail

DEST="${HOME}/.local/bin"
FROM=""
BUILD=1
REPLACE_SYMLINK=0
NAME="objdiff-cli"

while [ $# -gt 0 ]; do
    case "$1" in
        --dest) DEST="$2"; shift 2 ;;
        --from) FROM="$2"; BUILD=0; shift 2 ;;
        --name) NAME="$2"; shift 2 ;;
        --no-build) BUILD=0; shift ;;
        --replace-symlink) REPLACE_SYMLINK=1; shift ;;
        -h|--help) sed -n '2,26p' "$0"; exit 0 ;;
        *) echo "unknown argument: $1" >&2; exit 2 ;;
    esac
done

repo_root=$(cd "$(dirname "$0")/.." && pwd)

if [ "$BUILD" = 1 ]; then
    # Build into a directory of our own. Building into the tree's default
    # target/release is how the shared-symlink problem gets re-created.
    target_dir="${CARGO_TARGET_DIR:-$repo_root/target/install}"
    echo "building objdiff-cli into $target_dir"
    ( cd "$repo_root" && cargo build --release -p objdiff-cli --target-dir "$target_dir" )
    FROM="$target_dir/release/objdiff-cli"
fi

[ -x "$FROM" ] || { echo "no binary at $FROM" >&2; exit 1; }

target="$DEST/$NAME"
if [ -L "$target" ] && [ "$REPLACE_SYMLINK" = 0 ]; then
    echo "$target is a SYMLINK to $(readlink -f "$target")." >&2
    echo "Someone chose that, and replacing it changes what every process on this" >&2
    echo "box measures with. Re-run with --replace-symlink if that is intended." >&2
    exit 3
fi

version_line=$("$FROM" --version)
commit=$(cd "$repo_root" && git rev-parse --short=12 HEAD 2>/dev/null || echo "")
dirty=""
if [ -n "$commit" ] && [ -n "$(cd "$repo_root" && git status --porcelain --untracked-files=no)" ]; then
    dirty="-dirty"
fi
sha=$(sha256sum "$FROM" | cut -d' ' -f1)
# The same xxh3 the binary reports of itself and stamps into every report.
xxh3=$(printf '%s' "$version_line" | sed -n 's/.*xxh3 \([0-9a-f]*\).*/\1/p')

mkdir -p "$DEST"
# Write beside the target and rename, so no reader ever sees a half-copied file
# and nothing is destroyed if the copy fails.
tmp=$(mktemp "$target.XXXXXX")
cp "$FROM" "$tmp"
chmod 755 "$tmp"
mv -f "$tmp" "$target"

cat > "$target.provenance.json" <<EOF
{
  "installed": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "version_line": "$version_line",
  "git_commit": "$commit$dirty",
  "xxh3": "$xxh3",
  "sha256": "$sha",
  "source": "$FROM",
  "repo": "$repo_root"
}
EOF

echo "installed $target"
echo "  $version_line"
echo "  sha256 $sha"
echo "  manifest $target.provenance.json"
if [ -n "$dirty" ]; then
    echo "  WARNING: built from a DIRTY tree; the commit above does not describe these bytes." >&2
fi
